### ISSUE TITLE
Generate the thumbnail of dataset from the image format (JPG/PNG)

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/ckanext-odm_dataset#230]
Currently, the thumbnail of dataset on CKAN is automatically generated from the PNG only. 
As most of ODC maps/images are in JPG, I would like to suggest to update the code to generate the thumbnail from either JPG/PNG which are available.

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/commit/cbff023a28f1b56591cce3f649f73c289642e740
