### ISSUE TITLE
Implement fallback for missing multilingual data

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_dataset#259]
For every fluent field, pre-propulate the input component (text or markdown) with the non-multilingual value. this would be a better interim solution for those records which have not been migrated to multilingual per script yet and would remove the need of using the current "Record not migrated" warning

**Comment by chris-aeviator** [comment]
@acorbi 

can you give a status update on this / are you still working on it

**Comment by acorbi** [comment]
im still working on it. does it block your work somehow?
--
Gesendet von der myMail-App für Android Freitag, 11 März 2016, 11:53vorm. +01:00 von chris-aeviator < notifications@github.com> :

**Comment by chris-aeviator** [comment]
@acorbi 
thanks for your quick response

**Comment by acorbi** [comment]
:+1: ok! I will try to close that Issue this WE, but cannot promise...
