### ISSUE TITLE
Multilingual title in CKAN not displaying

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#262]
The title in all records should be multi-lingually enabled and the translators have been able to enter these titles in however upon saving them the display only shows the English when selecting the Khmer view. 

![ckan-bug-title](https://cloud.githubusercontent.com/assets/14996905/12881976/5d981398-ce4e-11e5-8283-46e7e28f066a.JPG)
![ckan-bug-title2](https://cloud.githubusercontent.com/assets/14996905/12881977/5d98f3f8-ce4e-11e5-8bec-25cf0df3a239.JPG)

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/commit/adf5ebee8e0cb2a9fa7b0b070217a789e7938dca
