### ISSUE TITLE
Search Function not consistent

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#266]
![ckan-search](https://cloud.githubusercontent.com/assets/14996905/13399318/f90d13cc-df02-11e5-8d33-3d320b531329.JPG)

I entered this search for sub-decree No. 405 in the top right hand corner and it doesn't not display the reference at all. Even if it appears in the main search window. I enter it in again several times but I never seem to get any results from a the laws section. 

I only manage to get the result i want when I specifically select laws and then the search in the main large search box. 

![ckan-search2](https://cloud.githubusercontent.com/assets/14996905/13399368/3b694fce-df03-11e5-9b33-629752865662.JPG)

I should be able to use any window and still find the correct document - particularly if I know the exact name and number of a law.

**Comment by acorbi** [comment]
@prustar thanks for logging this Issue in such good detail.

I checked the configuration in CKAN and noticed that the **ckan.search.show_all_types** variable was not set.  When set to true, the searches done on the homepage and header consider also custom dataset types ( which are our library and laws records ). Read http://docs.ckan.org/en/latest/maintaining/configuration.html?highlight=configuration%20file#ckan-search-show-all-types

I have enabled it both in PROD and PP and now this Issue cannot be reproduced. Closing....

Ping @DBishton , @jpeizer1, @Huyeng , @gimmemochi
