### ISSUE TITLE
fill maintainer automatically while creating datasets

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_dataset#278]
currently, maintainer and maintainer email fields are not being set ( are null ). which makes it difficult to know who created/modified a dataset.

**Comment by prustar** [comment]
Could you also include here the date it was loaded into CKAN.

**Comment by prustar** [comment]
Thanks for opening this issue - I hadn't seen it before. The above comment referes to making the data loaded into CKAN as an auto time stamp without the user having to input. This reduces the number of dates they need to input thus reducing confusion.

**Comment by acorbi** [comment]
@prustar ckan stores a timestamp already for all records. If you see https://data.opendevelopmentmekong.net/api/3/action/package_show?id=bti-2016-myanmar-country-report you'll find the metadata_created among the other fields

**Comment by prustar** [comment]
@acorbi So can we remove this field from the datasets so that people don't have to enter that value in? It can (and has) caused errors and confusion for data entry personnel.

**Comment by acorbi** [comment]
the maintainer field is **hidden** which means that the users entering the information would not see it, it will get populated "automagically". It appears in the table with all the metadata on a dataset's page. Example: https://data.opendevelopmentmekong.net/dataset/protected-areas?type=dataset

![screenshot from 2016-05-18 08-22-51](https://cloud.githubusercontent.com/assets/384894/15349282/f67656b6-1cd1-11e6-8f2d-8e639e226851.png)
