### ISSUE TITLE
Inappropriate resources loaded into CKAN find and deleted

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#279]
It has been raised that links to websites have been added into CKAN inappropriately. Example: 
https://data.opendevelopmentmekong.net/library_record/final-results-of-cambodian-2011-economic-census

These need to be found, made private so that we can double check if they are indeed only links, find the associated resources to them and add the links into these datasets within the source field. Then deleted.

**Comment by prustar** [comment]
Would it possible to automate this process of discovering these file types?

**Comment by acorbi** [comment]
@prustar you can filter out datasets with HTML resources by following this link: https://data.opendevelopmentmekong.net/dataset?res_format=HTML&_res_format_limit=0

This will show you all the datasets with links on it but it might include valid links to geoserver resources as well. So you still need to go through the list and identify the incorrect ones.

**Comment by DBishton** [comment]
@acorbi would it be possible to filter for datasets that contain _only_ HTML resources? 

@prustar I think there would be a fairly small number that meet the problematic criteria you describe (only external HTML links as resources).

**Comment by acorbi** [comment]
@DBishton unfortunatelly not that i know. But applying that filter URL i sent you reveals 80 datasets to review. that should not take much time

**Comment by acorbi** [comment]
@DBishton @prustar can we close this Issue?
