### ISSUE TITLE
Error when accessing profile tab in CKAN

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#282]
![image](https://cloud.githubusercontent.com/assets/14996905/15127195/d37a676c-1635-11e6-813d-6050a132e805.png)

**Comment by prustar** [comment]
Is this tab suppose to bring up all of the reference documents for individual profile pages? It's new so I wasn't clear what it would lead to but it just gave me this error message.

**Comment by acorbi** [comment]
Fixed on odm-frontend
