### ISSUE TITLE
Resource view not available

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#283]
I thought this was just a problem with a Myanmar resource that was loaded yesterday but ODC has now reproduced the error: 

https://data.opendevelopmentmekong.net/dataset/oil-and-gas-block-in-cambodia-2007-2014/resource/2f98963a-f855-493e-84d6-1317dd0558c4?type=dataset
![image](https://cloud.githubusercontent.com/assets/14996905/15139102/518d3928-1694-11e6-9022-8af0501acca8.png)

**Comment by acorbi** [comment]
I cannot reproduce this issue. @prustar can you still reproduce it? If not, please close issue.

**Comment by prustar** [comment]
It seems to have resolved itself? I tried both on Chrome and firefox. Thanks,
