### ISSUE TITLE
Implement ML support for resources

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#285]
https://data.opendevelopmentmekong.net/dataset/edit/sub-decree-no-157-on-establishment-of-neang-kok-koh-kong-sez

![image](https://cloud.githubusercontent.com/assets/14996905/15207427/82818136-1826-11e6-83d5-d42f431c6a3a.png)

Resource text has been translated and maintains the local language even in the English page.

**Comment by acorbi** [comment]
@prustar metadata for resources does not have multilingual functionalities. We could study implementing it though...

**Comment by prustar** [comment]
I mean that when the resource title is translated it overrides the English. After this mornings training with Myanmar there are still some glaring inconsistencies in the multilingual functionality. Wondering if this has been added to TWPM as a task to smooth out.

**Comment by acorbi** [comment]
@prustar As I said, multilingual support for resources' metadata is not enabled. That means that there can be only 1 title/description for resources (therefore overriding).

Adding this to https://odinitiative.teamworkpm.net/tasks/6245085

**Comment by prustar** [comment]
@acorbi Is there a place where all of these are being collated? Seems that there are a few places that need it enabled and also some additional work in transifex by partners.

**Comment by acorbi** [comment]
@prustar please elaborate on that. Which places need multilingual enabled? There is only datasets and resources... Translations on transifex refer to UI not content, therefore do not have anything to do with the multilingual support in CKAN records...

**Comment by prustar** [comment]
@acorbi I raised this during partner meeting and I believe @gimmemochi has been discussing this with you in the last few days. It is a mixture of issue which need to be investigated to see if it's because the strings haven't been translated in transifex or there are glitches. I specifically outlined steps in the notes of that meeting: 

Finalized the CKAN localization by the end of next week so that Alex can implement multi-lingual support
- There are inconsistencies in the translation and potentially some bugs. 
- There needs to be a review of what has and hasn’t been translated in transifex.
- Finalise these translations - by next week for Myanmar at least. 
- Log the bugs with the multilingual functionality across the three languages to see if the problem is duplicated across the languages or just affecting one language. 
- Provide the list to Alex and development team to have resolved.  

https://docs.google.com/document/d/1ZvUrtFhu6wBLfCdiecDbEb9xQGFCl9crNCKmxAH8gAI/edit
