### ISSUE TITLE
Tree cover image not displaying in CKAN

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#297]
Image not displaying: 

![image](https://cloud.githubusercontent.com/assets/14996905/15464504/1295ffd4-20d0-11e6-9949-0fd028fe498d.png)

**Comment by acorbi** [comment]
@prustar Fixed. The resource was not an Image (PNG) but a link to geoserver's open layers viewer. I have changed the format from PNG to HTML and now it renders accordingly.
