### ISSUE TITLE
Provide a cancel button or option for no autosave of incomplete records 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#323]
@acorbi I got notification of a record which was incomplete and erroneous, so I contacted the creator and essentially what had happened was that the record was automatically saved after some time regardless of exiting the entry. This record had the min requirement entered in. 

Is there possibility of editing the autosave options by making a popup up window to save the resource or not before exiting? Otherwise a does the delete button do this or do we need a cancel button?

**Comment by acorbi** [comment]
@prustar As long as I understang correctly, there is no auto-save function built in on CKAN.... If you modify a dataset's metadata or resource and try to leave the page without saving, the browser is going to present a popup like pictured below. That is standard behaviour for browsers when working with forms ( html <form> element ) as is the case here.

![screenshot from 2016-06-06 10-06-55](https://cloud.githubusercontent.com/assets/384894/15815634/ac73ab84-2bce-11e6-98ac-f5f426483fd9.png)

Should we close this then?

**Comment by prustar** [comment]
Not sure that this has happened again. If it repeats then I will raise again.
