### ISSUE TITLE
View CSV records

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/ckanext-odm_dataset#330]
I find this on CKAN - Natural Protected Area (Kh): https://data.opendevelopmentmekong.net/en/dataset/protectedareas/resource/eeef08fe-331e-4bb7-b03f-5b8df9b62114?type=dataset

![screenshot_1](https://cloud.githubusercontent.com/assets/18528756/16411993/26780fe2-3d54-11e6-935b-b4ae7a72dace.png)

Then I tried download the CSV excel file, and the data is there. I think it is a view issue on Ckan.

**Comment by prustar** [comment]
Is this related to this issue: #328

**Comment by acorbi** [comment]
Fixed, closing
