### ISSUE TITLE
Entering in CKAN records in any Language first

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#332]
Often partners want to enter records in the local language first before translating. Currently CKAN only allows for the language switch once the English records has been created. I have asked partners in the interim to place a 'space' in the mandatory English fields - save and then switch to the local language. Is this a bug or a function not yet enabled?

**Comment by acorbi** [comment]
@prustar this is a bug. Adding it to my list of things to tackle asap.

**Comment by jpeizer1** [comment]
@acorbi @prustar  Am wondering if a space is the best idea if "something" has to be added. Maybe a standrad phrase like "English Trans not available" or something -- the problem with Spaces is you don;t see them so you dont know they are there and they could play havoc with searches.

**Comment by acorbi** [comment]
@prustar @DoLinh This Issue has now being fixed and deployed on PP and PROD. Now, it is possible to create datasets in a non-default language first ( other languages than english ). Following considerations:

- Normally the name of a dataset, which is used on the url (e.g https://data.opendevelopmentmekong.net/dataset/some-name) is generated out of the title specified. Now when you create a new dataset in Khmer, Vietnamese or Burmese and specify a title with no english characters (e.g បណ្ដុំ​នៃប្រភព​​ទិន្នន័យ​ or ခေါင်းစဥ်) on it, CKAN will generate a unique id (e.g e38b79e6-6ed3-4212-a257-89aaa4bec9bb) which will be set as the dataset's name. 

- This means that if the user selects English as the current language, the dataset's name ( the id just generated) will be shown. Which is not nice. Therefore, the English version of the title should be added as soon as possible to avoid those IDs being visible on other parts.

![screenshot from 2016-07-06 18-15-23](https://cloud.githubusercontent.com/assets/384894/16625648/e2c7f0fc-43a5-11e6-9a53-ce1af9e47b8d.png)

![screenshot from 2016-07-06 18-15-33](https://cloud.githubusercontent.com/assets/384894/16625652/e8061b98-43a5-11e6-9ce9-abaee7a2bafc.png)

**Comment by prustar** [comment]
@acorbi @DoLinh - So it's probably best to still add the English translation? OR does this then imply that they need to fill in the mandatory fields with some content?

**Comment by acorbi** [comment]
I would say the best solution would be to:
1. Create the dataset in Vietnamese
2. Switch the language to English, click on MANAGE and specify a title in English

This way the mandatory fields are entered in vietnamese and those IDs do not appear anywhere when the English language is selected.
