### ISSUE TITLE
Process and Source Fields need to be Mandatory 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#335]
@acorbi - we changed these so that they would support multilingual function but they need to be mandatory. Adding this as a **to do** as the partners are uploading so many resources and they are missing these vital fields. Will save us time going back to fix all of these missing entries. 

Can we add in the audit records missing Process and Source as well so I can haggle people to fill them in as they go?

**Comment by prustar** [comment]
@acorbi -- just tested this upload dataset and it allowed me to upload without source and process. see: https://data.opendevelopmentmekong.net/dataset/test

It also created 3 resource documents when I only uploaded one?

**Comment by acorbi** [comment]
@prustar we do testing in **Pre-Production**, so please go to http://data.pp.opendevelopmentmekong.net/ and test there.

> It also created 3 resource documents when I only uploaded one?

if you can reproduce this issue, please raise it on github

**Comment by prustar** [comment]
@acorbi -- it worked on the english site but when I went to translate into Khmer it allowed me to save the record without source and process. Please ensure that the fields are mandatory for all languages. 

e.g. https://data.pp.opendevelopmentmekong.net/km/dataset/gvsrejkgoprkvf

**Comment by acorbi** [comment]
Hey @prustar that's correct. The current implementation only makes sure that the English version of those fields has been entered thus making it mandatory to enter the english version of the record first. 

I will change it so it ensures that the fields are mandatory for all languages as you suggest. reopening...

**Comment by prustar** [comment]
@acorbi -- all good and thanks also for making fields in resource page mandatory. Not a big issue but when you update a record and translate it it would be nice to have a notification for data/editor staff to remember to translate the metadata for there resource as well. Will raise a issue but it's not urgent.

**Comment by acorbi** [comment]
ok, deploying to prod. and yeah, please file that feature request
