### ISSUE TITLE
Extend list of supported countries

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_dataset#346]
Currently, staff members creating/editing CKAN records can select the following options for the **Geographic area (odm_spatial_range)**:
- Global
- ASEAN
- Greater Mekong Subregion (GMS)
- Lower Mekong Basin
- Lower Mekong countries
- Cambodia
- Vietnam
- Laos
- Thailand
- Myanmar
  
  (![screenshot from 2016-10-27 12-44-00](https://cloud.githubusercontent.com/assets/384894/19764400/1631d8fe-9c43-11e6-8f05-a23ed60b7cf6.png)

While this allows to address the possibility of adding CKAN records which relate to countries outside the mekong region and allows to select also specific regions (and not countries), it has some implications in terms of the way the data is maintained and the logic we want to implement for exposing country-specific data in the metadata forms, while being pulled from the data tables.

My concrete proposal would be that:
- Only the main 5 countries are exposed 
- If editors need to select regions (including the whole region), they would select some (or all) of them.
- When editors select (or deselect) one of the countries, the selectable options on the metadata fields that depend on the country variable would get automatically adapted.

@prustar please review this and provide feedback asap. This is my proposal to finalize the meta-data form for the laws.

**Comment by prustar** [comment]
@acorbi - This approach sounds reasonable. But please clarify the last bit of point 3, I'm not sure what you meant by the automatic default here.

**Comment by acorbi** [comment]
@prustar thinking about the regions you specified on https://docs.google.com/spreadsheets/d/1vPr-8t7gAB-8DB7G6Q4rfFVE12czBTlOjttI7MUK_pw/edit#gid=0

```
Lower Mekong Countries = kh, vn, la, th, mm
GMS = kh, vn, la, mm, cn (Yunan and Guangxi)
Lower Mekong Basin = kh, vn, la, th, mm
ASEAN = id, my, ph, sg, th, bn, kh, la, mm, vn.
South East Asia = th, vn, kh, la, mm, my, id, sg, ph, bn, cx, tl, cc
Mekong Basin = kh, vn, la, th, mm, cn
```

Should we add all these country codes to available options on the **Geographic range** field? Should we add ALL countries?

Looking forward to hear your thoughts.
