### ISSUE TITLE
Show titles instead of names/id on odm_related_*_records preset

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_dataset#348]
Currently, the ckanext-odm_dataset exposes presets for form fields which allow the editor to select existing datasets on CKAN. The presented dropdown box shows currently the name/id of the records which is not so user friendly.

![screenshot from 2016-11-14 14-17-43](https://cloud.githubusercontent.com/assets/384894/20266153/1f72da54-aa75-11e6-8842-3209121055dd.png)

**Comment by prustar** [comment]
@acorbi -- this is not the only case it also appears in other fields which are presented in the WP front end on the detailed metadata pages. See screen shot below of 'document type' and 'language' field. 

![image](https://cloud.githubusercontent.com/assets/14996905/21298035/9210431a-c5de-11e6-9817-68b45d02d288.png)

**Comment by acorbi** [comment]
This issue  has been fixed via 568ec38d05cab34050b5f682a8c4fb7a1419204f

@prustar The issues you just raised on your last comment have been addressed in part on 
https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/636. There is still an improvement on the logic to be made so the languages appear properly indicated (English instead of en, Khmer instead of km) when the record has more than 1 language. I'm opening a separate issue on https://github.com/OpenDevelopmentMekong/wpckan/issues/213
