### ISSUE TITLE
file formats generated

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#366]
@Huyeng @vatana92 - I've noticed for a couple of records recently that there has been other document types presented as well as pdf for reports such as the example below - JSON/MARC21/MARCXML. Are these being automatically updated or are editors generating them? They don't mean anything and I don't think they are useful to users so is there a reason to include them? 

![image](https://cloud.githubusercontent.com/assets/14996905/21129503/fa7ac73c-c155-11e6-9814-277b0935600e.png)

**Comment by acorbi** [comment]
I can reply to this. Those are bibliographic formats which were automatically generated during the migration process of ODC's old library into the new system
--
Gesendet von der myMail-App für Android Dienstag, 13 Dezember 2016, 07:06vorm. +01:00 von prustar  notifications@github.com :

**Comment by acorbi** [comment]
Closing this Issue. @prustar re-open if you consider....
