### ISSUE TITLE
Allow metadata form to be downloaded or accessible to user

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#367]
@acorbi - Feedback from ODMyanmar launch from users suggest that we make the metadata template that is attached to all records downloadable for their future reference with the data/information they accessed. Suggest to include a download metadata button that generates either a text or XML formatted file for users to download when they are accessing records. 

@thetaung2 - thanks for raising, was there another solution that you were thinking about?

**Comment by acorbi** [comment]
Sounds good!
I suggest to link them directly to the corresponding JSON file expoaed by CKAN Api, both in JSON and RDF.
it is a quick one, will do later today
--
Gesendet von der myMail-App für Android Dienstag, 13 Dezember 2016, 07:09vorm. +01:00 von prustar  notifications@github.com :

**Comment by prustar** [comment]
@acorbi -- please don't geek it out, lets keep it simple so that people can use the information. Not everyone reads or understands JSON files it's not common for everyday use and RDF is only necessary for sharing which is not what this user is asking for.  We of course can supply these as well for the tech savy but for general usability a **text file** would suffice.

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/653 and already deployed on PP.

@prustar From https://en.wikipedia.org/wiki/JSON:

> In computing, JSON (canonically pronounced /ˈdʒeɪsən/ JAY-sən;[1] sometimes JavaScript Object Notation) is an open-standard format that uses **human-readable text** to transmit data objects consisting of attribute–value pairs.

The idea of an open data platform is to provide its users access to the data and its metadata for them to be used, re-used and re-distributed. To achieve this, one needs to, not only publish the data under open licenses but also to stick to open standards and expose the data and metadata in formats that encourage its re-usability both by humans and machines.

According to http://5stardata.info/en/ exposing data as a text-file is somewhere between the 1st and 3rd star. Exposing it via JSON its 3-star data. Exposing it via RDF (which is XML btw, you were suggesting to use XML) is 5-star data.

So, I would say those users for which a text-file would suffice, can select and copy the text directly from the website.
