### ISSUE TITLE
PROCESS & SOURCE metadata fields

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#370]
@acorbi  -- just remembered that these two fields are still not mandatory and need to be. When you convert staging to prod next week can you please make sure that the issue preventing these from being mandatory be corrected so that they can be made mandatory once again.

**Comment by acorbi** [comment]
@prustar I'm adding it to the list of tasks for the review of 2.1 but I'm not sure I can complete if by the end of this development cycle.

**Comment by acorbi** [comment]
BTW, this is duplicated. Closing this in favour of https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/335
