### ISSUE TITLE
No issues button on this record?

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#374]
![image](https://cloud.githubusercontent.com/assets/14996905/21536641/58d00ef2-cdd9-11e6-93d0-cb0016601c6c.png)

This library record has been entered incorrectly and needs to be moved. I was going to raise an issue and have it assigned to someone but I can't because there is no issues tab?

**Comment by acorbi** [comment]
@prustar this should be fixed now. Closing...

FYI: I fixed it by:
- clicking on manage
- clicking on save

Please re-open if you can still reproduce the issue.
