### ISSUE TITLE
LibreBASE edits

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#375]
@acorbi -- 

I'm updating tables using the database we set up but there's something strange going on. 

In both tables issuing agent and implementing agent there are no names actually listed. When I go to edit the names and make an entry and save it in the second column it duplicates it in each of the rows? 
Everytime I save it it simply saves what I last entered into that column? 
1. I entered in the corresponding value in column 2: 
![image](https://cloud.githubusercontent.com/assets/14996905/21754913/b0a92d66-d65d-11e6-8b7c-faa36adeb9a1.png)
2. I select another record and it keeps the same value above for row 1: 
![image](https://cloud.githubusercontent.com/assets/14996905/21754921/d1297cbc-d65d-11e6-86ac-b8ffa6a908a0.png)
3. Implementing agency table with nothing present in column 2: 
![image](https://cloud.githubusercontent.com/assets/14996905/21754928/ea6c5fbe-d65d-11e6-8e62-4aa5ea2d8539.png)

**Comment by acorbi** [comment]
Hi @prustar I have sent you an email with another Libreoffice base file, the problem should be solved with that one.

One thing I would like to remark is that you need to click save after you make a change in order for this to be applied. 

Closing this, please re-open if you have further problems with the new file
