### ISSUE TITLE
More license options needed in "License" field

### ISSUE THREAD

**Issue by thetaung2** [OpenDevelopmentMekong/ckanext-odm_dataset#379]
Partners shared their documents to be uploaded onto the portal. But the CKAN License field options doesn't include CC BY 3.0 IGO and CC-BY-SA 3.0 IGO. 

![myanmar adp report](https://cloud.githubusercontent.com/assets/20394487/21841577/1ff0777e-d811-11e6-9de6-11f5b0748c8d.PNG)
![myanmar mdi report](https://cloud.githubusercontent.com/assets/20394487/21841578/201fe95a-d811-11e6-9bbe-a3bada6af81d.PNG)

**Comment by acorbi** [comment]
Moving this to https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/issues/72. Closing
