### ISSUE TITLE
Data refactoring for document_type

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_dataset#381]
The field document_type ( library_record) present some inconsistencies, following actions to be undertaken:

- [ ] Migrate all records tagged with **Company Profiles** to **Archived web-content** (300 in PP, 289 in PROD)
- [ ] Migrate all records tagged with **Profile-People** to **reports** (1 in PP)
- [ ] Migrate all records tagged with **Profiles-Organisations and projects** to **reports** (42 in PP)
- [ ] Add entry **EIA/SEIA** to list

**Comment by acorbi** [comment]
@ChandaraKhun @prustar please confirm that the actions to undertake are correct.

**Comment by prustar** [comment]
@acorbi -- yes this sounds fine. Needs to be updated in Wiki - will put on list to do shortly.

**Comment by acorbi** [comment]
For reference:

```UPDATE package_extra set value ='archived_web_content' WHERE key = 'document_type' and value = 'company_profiles'```

**Comment by acorbi** [comment]
Done via SQL scripts
