### ISSUE TITLE
uploading resource in CKAN produced multiple files

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#382]
Did this in Production yesterday and now pp and reporduced the error. 

I only uploaded one file in the resources section and it produced a list of 2 additional resources. 

![image](https://cloud.githubusercontent.com/assets/14996905/22091291/9fcb0038-de4a-11e6-9dca-f17d0ae46f38.png)

As a test I just added a link to bbc.com site, additional resources are a screen grab of the header of one of our pages and the surface water map? Very very strange behaviour.

**Comment by acorbi** [comment]
@prustar noted, will address it today.

**Comment by acorbi** [comment]
@prustar I have been trying to reproduce this issue on PP but could not. can you provide concrete steps to reproduce it? Also, please provide following details:

- Did it happen while adding a resource of an existing record? or it happened while creating a new one?
- Did it happen with a dataset, library record or laws record?

**Comment by prustar** [comment]
@acorbi - tested this while checking issue - 335 and it didn't happen. Will go through again next week to check if it still happens.

**Comment by acorbi** [comment]
closing tn, please reopen if it reappears
