### ISSUE TITLE
Manditory field request

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#383]
On the resource page of CKAN when entering in the metadata the All of the fields should be mandatory (except Format as this is autofilled). 
![image](https://cloud.githubusercontent.com/assets/14996905/22095287/a9553930-de67-11e6-8175-5d72dc0d00ab.png)

As language is not currently mandatory many records don't list the language of the resource which limits search filter option for language and the descriptions are often not adequate to tell the user what the resource contains.

**Comment by acorbi** [comment]
@prustar noted, will implement soon

**Comment by acorbi** [comment]
@prustar fixed and deployed to PP. please test
