### ISSUE TITLE
Cannot add new resource in dataset

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/ckanext-odm_dataset#396]
CKAN has a problem with uploading new resource or update the resource in the published dataset. For example, I want to upload a new resource in the dataset(https://data.opendevelopmentmekong.net/dataset/economiclandconcessions)
![image](https://cloud.githubusercontent.com/assets/18112596/22723629/a9fd4838-edf2-11e6-9a4f-fddd2bd8a248.png)

After I click add
![image](https://cloud.githubusercontent.com/assets/18112596/22723639/b81d4512-edf2-11e6-9351-a129418e02b7.png)

It is still the same.

**Comment by acorbi** [comment]
hey @punwath thanks for raising this. Will check it out today

**Comment by prustar** [comment]
@punwath the resource fields for name, description and language are now mandatory - you need to enter something in all these fields now before you can save. Have you tried this?

**Comment by punwath** [comment]
@pyrou I filled all the required field already but it still exists.

**Comment by acorbi** [comment]
@punwath @prustar I found the origin of the Issue, let me explain it and provide instructions to fix it:

## Reason

In the last weeks we have done some changes in the metadata fields which provoque existing records to be in a "inconsistent" state:

- Process(s) and Source(s) fields in datasets are now mandatory
- Title and description in resources for all record types are now mandatory

If you notice, one of the resources of the records in question (https://data.opendevelopmentmekong.net/dataset/economiclandconcessions) is missing its description:

![screenshot from 2017-02-08 10-31-40](https://cloud.githubusercontent.com/assets/384894/22731592/72c4ac64-edeb-11e6-8c9f-38c2efe9ce43.png)

When @punwath then tries to add a new resource, CKAN first checks that all the data is complete and fails to create it, as raised by punwath.

## Fix

If this situation happens, editors should check that both metadata and resources are complete. If Punwath adds a description to that resource missing it, then he will be able to add that new resource he wants to add.

Editors should be obviously alerted about this in any case, that is why I opened following issue to include a disclaimer or warning message for those records which are inconsistent:
https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/397

I'm closing this Issue, please re-open if my proposed fix does not work ( I tested it on PP already)
