### ISSUE TITLE
Improvements on keywords field

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_dataset#419]
You can't add keyword strings to the new field in CKAN for instance I wanted to include a keyword tag for a company name specifically 'Vesan Investments'. The field would only accept a single word for this name which is less than idea. 

We want to us the taxonomy as a structure to standardise terms for categorising them for monitoring but allow the keywords to be unstructured to be able to more intuitively fine tune the results from searches etc.  As there are no keywords as yet in the system when it was looking for them nothing came up. Is the field programmed to display related or similar terms when you type so as to avoid duplicates?

**Comment by acorbi** [comment]
@prustar ok, I will configure the field so keywords are set by hitting comma, tab or enter. But not whitespace.

> We want to us the taxonomy as a structure to standardise terms for categorising them for monitoring but allow the keywords to be unstructured to be able to more intuitively fine tune the results from searches etc. As there are no keywords as yet in the system when it was looking for them nothing came up. Is the field programmed to display related or similar terms when you type so as to avoid duplicates?

If I understand you correctly, you would suggest to add all the topics as suggestions, correct?

**Comment by prustar** [comment]
The parameters I'm suggesting for the keyword field are: 
- excludes all of the taxonomy terms by default so as not to have duplicates in both fields. This means that you can't tag something land if it is already tagged with taxonomy terms relating/identical to land 
- allow for multiple words - which you've addressed to capture terms or names. 
- Ensure that as a user is typing in a keyword that suggestions are offered to the data staff so as not to duplicate and maintain consistency in spelling i.e. ODI program vs. ODI programme same meaning different spelling.

**Comment by acorbi** [comment]
@prustar

> excludes all of the taxonomy terms by default so as not to have duplicates in both fields. This means that you can't tag something land if it is already tagged with taxonomy terms relating/identical to land

Created a separate issue for this: https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/420

> allow for multiple words - which you've addressed to capture terms or names.

done and deployed on PP. In order to set the tags, users need to hit comma or enter (tab does not work, it takes user to the next link)

> Ensure that as a user is typing in a keyword that suggestions are offered to the data staff so as not to duplicate and maintain consistency in spelling i.e. ODI program vs. ODI programme same meaning different spelling.

Separate issue: https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/421
