### ISSUE TITLE
Disallow editors entering tags on keywords field

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_dataset#420]
Excludes all of the taxonomy terms by default so as not to have duplicates in both fields. This means that you can't tag something land if it is already tagged with taxonomy terms relating/identical to land

**Comment by prustar** [comment]
@acorbi - The current implementation of removing the key terms after they have been entered isn't ideal. It's important for the data entry staff to enter in the correct taxonomic terms and keywords that would maximise the search. I think we need to make it obvious for them so they understand the differences. If a term is used in Keywords that is a Taxonomic term then they won't know that they should have entered it in that field. I understand how this is not logical but people don't know what the 500+ terms are and may not naturally try them all first before entering in the keywords. 

Secondly yes this should also be entered in for the various langues - we have these terms translated already so it should be the same implementation.

**Comment by acorbi** [comment]
Ok, will improve this so it is better understandable for editors. reopening

**Comment by acorbi** [comment]
@prustar I have implemented an improvement so an alert is displayed when a user enters a keyword which is already on the list of selected topics.

![screenshot from 2017-06-28 17-17-00](https://user-images.githubusercontent.com/384894/27645152-b6fe3956-5c25-11e7-8314-dc560a9e4ba9.png)
![screenshot from 2017-06-28 17-17-21](https://user-images.githubusercontent.com/384894/27645153-b720b580-5c25-11e7-9326-b27924e2867b.png)
