### ISSUE TITLE
Publication data on library record

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#424]
![image](https://cloud.githubusercontent.com/assets/14996905/24769327/4f18b914-1b30-11e7-8c4b-c761c3e61337.png)

Data on WP but in CKAN that record is recorded as 2016- https://data.opendevelopmentmekong.net/dataset/edit/an-overview-of-large-scale-investments-in-the-mekong 
![image](https://cloud.githubusercontent.com/assets/14996905/24769373/78dd242e-1b30-11e7-93cd-36ae9572735b.png)

**Comment by acorbi** [comment]
This is already fixed, closing.
