### ISSUE TITLE
Internal server error when resetting password

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/ckanext-odm_dataset#435]
Hi @acorbi,

I'm currently unable to access CKAN as I need to reset my password, and receive an 'internal server error' message when this is attempted.

**Comment by acorbi** [comment]
@DBishton I have tried to reproduce the issue but I could not. Can you please specify concrete steps to reproduce it on your side?

**Comment by DBishton** [comment]
Hi @acorbi,

I just tested this again and have the same issue. Steps are:

1. click 'log in'
2. click 'Forgot your password?'
3. Enter Username: "DBishton"
4. click 'Request reset'

**Comment by acorbi** [comment]
hey @DBishton 

Not sure why it throws the error, if I try other usernames such as "acorbi" and even some which do not exists such as "nonexistant", it does not throw it. Even if I try in caps like "ACorbi" it does not break.

Anyway, I tried with "dbishton" and apparently it worked, so you should have received an email for reseting the pwd. if not, please try again and update me.

**Comment by acorbi** [comment]
@DBishton WHat is the status of this issue? did you try my suggestion?

**Comment by acorbi** [comment]
@DBishton ping
