### ISSUE TITLE
CKAN private vs public view

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#443]
@acorbi -- When I view Gulshat's records which are private they show up under her user account: 
![image](https://user-images.githubusercontent.com/14996905/27345509-eebd3f5a-55b7-11e7-8d0f-9b5a0b2919c6.png)
https://data.opendevelopmentmekong.net/user/gmaatkerimova

When we both did a search in CKAN for each of these records (we are both ADMINS) we cannot find them:

![image](https://user-images.githubusercontent.com/14996905/27345554-21ccc4ec-55b8-11e7-8392-e3b4b5c85e1d.png)

WHY?

**Comment by acorbi** [comment]
As indicated on https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/issues/86, you need to search from within the organization's site. In the case of the first record it would be https://data.opendevelopmentmekong.net/organization/laos-organization

Question: Does she need to be admin? I would add her as editor first if there is no special requirement...

**Comment by prustar** [comment]
On the audit page: https://data.opendevelopmentmekong.net/audit#private-by-type

![image](https://user-images.githubusercontent.com/14996905/27345791-e074a216-55b8-11e7-80bb-a85235eda4d8.png)
Note the number of records for libraries

![image](https://user-images.githubusercontent.com/14996905/27345822-ff98e8c8-55b8-11e7-8ccd-cd1b9beebb5c.png)
The number of records is inconsistent and also none of these records are private?

**Comment by acorbi** [comment]
1806 are private library publications. Since they are private they do not appear on https://data.opendevelopmentmekong.net/library_record

if you add 1806 + 1742 (public ones) you get 3548 which is the total number of library publications -> https://data.opendevelopmentmekong.net/audit#records-by-type
