### ISSUE TITLE
Strange search behaviour

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#450]
@acorbi -- I do a text search for this title and it actually prompts me with a resource see first image, but when I select this it shows me a not found message. If I just do a normal text search and select search it finds the report no problems. 

![image](https://user-images.githubusercontent.com/14996905/28863771-89dc24be-776a-11e7-965d-95ee762ff9f7.png)

![image](https://user-images.githubusercontent.com/14996905/28863807-a6044aae-776a-11e7-8a86-742fa3d9f124.png)

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/206.
